---
version: "3"
services:
  db:
     container_name: db
     hostname: db
     image: postgres:11.5
     restart: always
     environment:
     - POSTGRES_USER=admin
     - POSTGRES_PASSWORD=admin
     - POSTGRES_DB=app-db
     ports:
     - 32769:5432
     volumes:
     - /var/lib/postgresql/data
     networks:
     - api

  adminer:
    # https://hub.docker.com/_/adminer/
    # https://github.com/vrana/adminer/tree/master/designs
    container_name: adminer
    hostname: adminer
    image: adminer:4.6.3-standalone
    restart: always
    environment:
    - ADMINER_DESIGN=nette
    ports:
    - 8080:8080
    networks:
    - api

networks:
  api: {}
